<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Library</OutputType>
    <PublishAot>true</PublishAot>
    <NativeLib>Shared</NativeLib>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <InvariantGlobalization>true</InvariantGlobalization>
    <StripSymbols>true</StripSymbols>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Product.cs" />
    <ProjectReference Include="../../csharp/Rusty.Engine/Rusty.Engine.csproj" />
    <ProjectReference Include="CsharpNativeAotTrial.Game.csproj" />
    <ProjectReference Include="../../csharp/Rusty.Engine.ProductGenerator/Rusty.Engine.ProductGenerator.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false" />
  </ItemGroup>
</Project>
