[package]
name = "product-assembly"
version.workspace = true
edition.workspace = true

[dependencies]
cap-primitives.workspace = true
cap-std.workspace = true
content-store.workspace = true
product-model.workspace = true
product-dev-host.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
toml.workspace = true

[lints]
workspace = true
