[package]
name = "gameplay-standard"
version.workspace = true
edition.workspace = true

[dependencies]
core-ids.workspace = true
entity-state.workspace = true
gameplay-mechanics.workspace = true
gameplay-resolution.workspace = true
gameplay-rules.workspace = true
serde_json.workspace = true

[lints]
workspace = true
