[package]
name = "csharp-product-runtime"
version.workspace = true
edition.workspace = true

[dependencies]
libloading = "0.8.9"
serde_json.workspace = true
csharp-engine-abi.workspace = true
csharp-engine-services.workspace = true
product-dev-host.workspace = true
product-model.workspace = true
render-presentation.workspace = true
runtime-input.workspace = true
runtime-lifecycle.workspace = true
runtime-ui.workspace = true
