[package]
name = "csharp-product-runtime"
version.workspace = true
edition.workspace = true

[dependencies]
libloading = "0.8.9"
product-dev-host.workspace = true
core-math.workspace = true
core-ids.workspace = true
core-space.workspace = true
engine-spatial.workspace = true
entity-state.workspace = true
render-model.workspace = true
render-projection.workspace = true
runtime-input.workspace = true
runtime-lifecycle.workspace = true
runtime-ui.workspace = true
serde_json.workspace = true
svc-pathfinding.workspace = true
