[package]
name = "render-projection"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
asset-catalog.workspace = true
core-assets.workspace = true
core-ids.workspace = true
engine-spatial = { path = "../engine-spatial" }
entity-state = { path = "../entity-state" }
render-model.workspace = true
serde.workspace = true
svc-mesh.workspace = true
voxel-object-runtime.workspace = true

[dev-dependencies]
base64.workspace = true
core-math.workspace = true
serde_json.workspace = true
voxel-asset.workspace = true
