// @generated by Rusty.Engine.BindingGenerator from its parsed C ABI model.
// Do not edit; run scripts/generate-csharp-native-bindings.sh.
use crate::NativeProductAbiFingerprint;

pub const PRODUCT_ABI_PROTOCOL_VERSION: u32 = 1;
pub const PRODUCT_ABI_FINGERPRINT: NativeProductAbiFingerprint = NativeProductAbiFingerprint {
    word0: 0x1FD68699E725B4EB,
    word1: 0xFC430F3E61A4DAEF,
    word2: 0x6AFB952C4BAC9C28,
    word3: 0x9733B9A93CA66156,
};
