// @generated by Rusty.Engine.BindingGenerator from its parsed C ABI model.
// Do not edit; run scripts/generate-csharp-native-bindings.sh.
use crate::NativeProductAbiFingerprint;

pub const PRODUCT_ABI_PROTOCOL_VERSION: u32 = 1;
pub const PRODUCT_ABI_FINGERPRINT: NativeProductAbiFingerprint = NativeProductAbiFingerprint {
    word0: 0x7EC04724B2C15ED8,
    word1: 0xAA1E05450DDE1E2E,
    word2: 0xD7B094D180643714,
    word3: 0x25D9140B1ED54182,
};
