// @generated by Rusty.Engine.BindingGenerator from its parsed C ABI model.
// Do not edit; run scripts/generate-csharp-native-bindings.sh.
use crate::NativeProductAbiFingerprint;

pub const PRODUCT_ABI_PROTOCOL_VERSION: u32 = 1;
pub const PRODUCT_ABI_FINGERPRINT: NativeProductAbiFingerprint = NativeProductAbiFingerprint {
    word0: 0x45DBFE10F6666307,
    word1: 0x4114E85393CDEB7D,
    word2: 0xD82516A5988A20EC,
    word3: 0x93C0395B91C30C98,
};
