// Generated by render/scripts/generate-depth-splat-fixture.mjs.
// Static URL expressions let Vite retain the checked fixture bytes.
export const DEPTH_SPLAT_MESH_RESOURCE_LOCATIONS = Object.freeze({
  "mesh-resource/137cb73ab461af6cdd156d2d0b5c6dd278af2f7d14b0e47c430f7221d1650bd0": new URL("../../fixtures/render/depth-splat/mesh-137cb73ab461af6cdd156d2d0b5c6dd278af2f7d14b0e47c430f7221d1650bd0.rmsh", import.meta.url).href,
  "mesh-resource/fdba7521d3d692a0993b6e5fd4da660b1b26f1acad9ca0b1fb3426080c69e394": new URL("../../fixtures/render/depth-splat/mesh-fdba7521d3d692a0993b6e5fd4da660b1b26f1acad9ca0b1fb3426080c69e394.rmsh", import.meta.url).href,
} as const);

export const DEPTH_SPLAT_TEXTURE_RESOURCE_LOCATIONS = Object.freeze({
  "texture-resource/5f34c8db37048eeb5df2b0eaf29f0098f489025c09f1f3ff0d4308eb6e43c34b": new URL("../../fixtures/render/depth-splat/texture-5f34c8db37048eeb5df2b0eaf29f0098f489025c09f1f3ff0d4308eb6e43c34b.png", import.meta.url).href,
} as const);
