using Microsoft.CodeAnalysis;

namespace Rusty.Engine.ProductGenerator;

[Generator]
public sealed class ProductGenerator : IIncrementalGenerator
{
    // Set by the product project and made visible to the compiler by the SDK
    // targets. Library projects that reference Rusty.Engine leave it empty.
    private const string EntryTypeProperty = "build_property.RustyEngineProductEntryType";

    private static readonly DiagnosticDescriptor MissingProductType = new(
        "RUSTY001",
        "Product entry type not found",
        "RustyEngineProductEntryType '{0}' does not name a type in this compilation or its references",
        "Rusty.Engine",
        DiagnosticSeverity.Error,
        true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValueProvider<string> entryType = context.AnalyzerConfigOptionsProvider
            .Select(static (options, _) => options.GlobalOptions.TryGetValue(EntryTypeProperty, out string? value) ? value.Trim() : string.Empty);
        context.RegisterSourceOutput(context.CompilationProvider.Combine(entryType), static (output, input) =>
        {
            (Compilation compilation, string entryTypeName) = input;
            if (entryTypeName.Length == 0) return;
            INamedTypeSymbol? product = compilation.GetTypeByMetadataName(entryTypeName);
            if (product is null)
            {
                output.ReportDiagnostic(Diagnostic.Create(MissingProductType, Location.None, entryTypeName));
                return;
            }

            DebugCommandCatalogGenerator.Generate(output, compilation, product);
            output.AddSource("ProductExports.g.cs", Exports(product));
        });
    }

    private static string Exports(INamedTypeSymbol product)
    {
        string type = product.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        // The Engine-owned bridge in Rusty.Engine holds the ABI plumbing. This
        // export is the product-specific part: its constructor and debug catalog.
        return $$"""
            // <auto-generated />
            #nullable enable
            namespace Rusty.Engine.NativeProduct;

            internal static class ProductExports
            {
                [global::System.Runtime.InteropServices.UnmanagedCallersOnly(EntryPoint = "rusty_product_bind_v1", CallConvs = new[] { typeof(global::System.Runtime.CompilerServices.CallConvCdecl) })]
                internal static int BindV1(nint host, nint product)
                    => global::Rusty.Engine.NativeProduct.ProductBridge.Bind(
                        host,
                        product,
                        static context => new {{type}}(context),
                        GeneratedDebugCommandCatalogFactory.Create);
            }
            """;
    }
}
