using Microsoft.CodeAnalysis;

namespace Rusty.Engine.ProductGenerator;

[Generator]
public sealed class ProductGenerator : IIncrementalGenerator
{
    private const string ProductAttribute = "Rusty.Engine.EngineProductAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterSourceOutput(context.CompilationProvider, static (output, compilation) =>
        {
            INamedTypeSymbol[] candidates = compilation.Assembly.GetAttributes()
                .Where(attribute => attribute.AttributeClass?.ToDisplayString() == ProductAttribute)
                .Select(ProductType)
                .Where(product => product is not null)
                .Cast<INamedTypeSymbol>()
                .ToArray();
            // The analyzer is carried transitively by Rusty.Engine. Most of
            // those compilations are ordinary libraries, not product roots;
            // do not add a bind export or require an attribute.
            if (candidates.Length == 0) return;
            if (candidates.Length != 1)
            {
                output.ReportDiagnostic(Diagnostic.Create(
                    new DiagnosticDescriptor("RUSTY001", "One NativeProduct selection is required", "Select exactly one product with [assembly: EngineProduct(typeof(...))]", "Rusty.Engine", DiagnosticSeverity.Error, true),
                    Location.None));
                return;
            }

            DebugCommandCatalogGenerator.Generate(output, compilation);
            output.AddSource("ProductExports.g.cs", Exports(candidates[0]));
        });
    }

    private static INamedTypeSymbol? ProductType(AttributeData attribute)
    {
        if (attribute.ConstructorArguments.Length != 1)
        {
            return null;
        }
        return attribute.ConstructorArguments[0].Value as INamedTypeSymbol;
    }

    private static string Exports(INamedTypeSymbol product)
    {
        string type = product.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        // The Engine-owned bridge in Rusty.Engine holds the ABI plumbing. This
        // export is the product-specific part: its constructor and debug catalog.
        return $$"""
            // <auto-generated />
            #nullable enable
            namespace Rusty.Engine.NativeProduct;

            internal static class ProductExports
            {
                [global::System.Runtime.InteropServices.UnmanagedCallersOnly(EntryPoint = "rusty_product_bind_v1", CallConvs = new[] { typeof(global::System.Runtime.CompilerServices.CallConvCdecl) })]
                internal static int BindV1(nint host, nint product)
                    => global::Rusty.Engine.NativeProduct.ProductBridge.Bind(
                        host,
                        product,
                        static context => new {{type}}(context),
                        GeneratedDebugCommandCatalogFactory.Create);
            }
            """;
    }
}
