[package]
name = "rusty-cli"
version.workspace = true
edition.workspace = true

[[bin]]
name = "rusty"
path = "src/main.rs"

[dependencies]
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
product-container.workspace = true
asset-import.workspace = true

[target.'cfg(unix)'.dependencies]
signal-hook = "0.3"

[lints]
workspace = true
