packages:
  - 'apps/*'
  - 'libs/*'
  - '../render/packages/render-contracts'
  - '../render/packages/render-projection'
  - '../render/packages/renderer-host'
  - '../render/packages/renderer-three'

allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  less: true
  lmdb: true
  msgpackr-extract: true
  nx: true

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - less
  - lmdb
  - msgpackr-extract
  - nx
