export {
  authorRuntimeComposition,
  compiledCompositionBytes,
  admitCompiledComposition,
  engineCapability,
  kernelCapability,
  intent,
  productIntent,
  inputAction,
  system,
  schedule,
  Standard,
  phase,
  scheduleAction,
  gameplayDefinition,
  gameplayCatalog,
  timeline,
  timelineStep,
  cadence,
  fragment,
  append,
  prepend,
  extend,
  replace,
  appendComposition,
  prependComposition,
  extendComposition,
  replaceComposition,
  MAX_COMPILED_COMPOSITION_BYTES,
  MAX_INPUT_MAP_ENTRIES,
  MAX_INTENT_DESCRIPTORS,
  MAX_INPUT_CHORD_CONTROLS,
  MAX_SCHEDULE_ENTRIES,
  MAX_GAMEPLAY_DEFINITIONS,
  MAX_TIMELINES,
  MAX_TIMELINE_STEPS,
  MAX_CAPABILITY_BINDINGS,
  MAX_SCHEDULE_RESOURCE_DECLARATIONS,
  MAX_SCHEDULE_DEPENDENCIES,
} from './author.js';
export { observePairs } from './observe-pairs.js';
export type { ObservePairsDraft, ObservePairsQuotas } from './observe-pairs.js';
export { RuntimeCompositionAuthoringError, type RuntimeCompositionAuthoringErrorCode } from './error.js';
export type { EngineCapabilityName, EngineCapabilityTarget } from './generated.js';
export type {
  CapabilityBinding,
  CompiledComposition,
  CompositionFragment,
  CompositionReplacement,
  GameplayDefinition,
  InputActionDraft,
  ProductIntentDescriptorDraft,
  ProductIntentDescriptor,
  IntentValueKind,
  InputTrigger,
  InputEdge,
  KeyboardControl,
  PointerButton,
  InputAxis,
  ControllerButton,
  ControllerAxis,
  InputMapEntry,
  JsonValue,
  RuntimeCompositionArtifact,
  RuntimeCompositionDraft,
  ScheduleCadence,
  ScheduleCompositionMode,
  ScheduleDraft,
  SchedulePhase,
  SchedulePhaseDeclaration,
  SchedulePlacement,
  ScheduleSystem,
  StandardPhase,
  ScheduleActionDraft,
  ScheduleEntry,
  ScheduleEntryDraft,
  Timeline,
  TimelineStep,
  TimelineStepDraft,
} from './types.js';
