export {
  authorRuntimeComposition,
  compiledCompositionBytes,
  admitCompiledComposition,
  engineCapability,
  kernelCapability,
  intent,
  inputAction,
  phase,
  scheduleAction,
  gameplayDefinition,
  gameplayCatalog,
  timeline,
  timelineStep,
  cadence,
  fragment,
  append,
  prepend,
  extend,
  replace,
  MAX_COMPILED_COMPOSITION_BYTES,
  MAX_INPUT_MAP_ENTRIES,
  MAX_SCHEDULE_ENTRIES,
  MAX_GAMEPLAY_DEFINITIONS,
  MAX_TIMELINES,
  MAX_TIMELINE_STEPS,
  MAX_CAPABILITY_BINDINGS,
  MAX_SCHEDULE_RESOURCE_DECLARATIONS,
} from './author.js';
export { RuntimeCompositionAuthoringError, type RuntimeCompositionAuthoringErrorCode } from './error.js';
export type {
  CapabilityBinding,
  CompiledComposition,
  CompositionFragment,
  CompositionReplacement,
  GameplayDefinition,
  InputActionDraft,
  InputMapEntry,
  JsonValue,
  RuntimeCompositionArtifact,
  RuntimeCompositionDraft,
  ScheduleActionDraft,
  ScheduleEntry,
  ScheduleEntryDraft,
  Timeline,
  TimelineStep,
  TimelineStepDraft,
} from './types.js';
