import { RuntimeCompositionAuthoringError } from './error.js';
import {
  MAX_CAPABILITY_BINDINGS,
  MAX_COMPILED_COMPOSITION_BYTES,
  MAX_SCHEDULE_RESOURCE_DECLARATIONS,
  admitCompiledComposition,
  authorRuntimeComposition,
} from './author.js';
import { PRODUCT_MODEL_IDENTITY } from './generated.js';
import { compareUtf8, utf8Length } from './json.js';
import type {
  CapabilityBinding,
  CompiledComposition,
  RuntimeCompositionArtifact,
} from './types.js';

/** The versionless Rust Product Kernel contract artifact. */
export const PRODUCT_KERNEL_ARTIFACT = 'product-kernel' as const;

export type ProductKernelCapabilityKind =
  | 'system'
  | 'operation'
  | 'query'
  | 'projection';

export type ProductKernelCapabilityUse = 'input-map' | 'schedule' | 'timeline';
export type ProductKernelCapabilityTarget = `kernel.${string}`;

export interface ProductKernelCapabilityAccess {
  readonly reads: readonly string[];
  readonly writes: readonly string[];
}

export interface ProductKernelCapabilityBudget {
  readonly maximumCompactJsonPayloadBytes: number;
}

export interface ProductKernelCapabilityProvenance {
  readonly owner: string;
  readonly source: string;
  readonly logicalPath: string;
}

/** One generated downstream owner descriptor. It contains metadata only. */
export interface ProductKernelCapabilityDescriptor {
  readonly identity: string;
  readonly target: ProductKernelCapabilityTarget;
  readonly kind: ProductKernelCapabilityKind;
  readonly uses: readonly ProductKernelCapabilityUse[];
  readonly availability: 'linkable' | 'unavailable';
  readonly access: ProductKernelCapabilityAccess;
  readonly budget: ProductKernelCapabilityBudget;
  readonly provenance: ProductKernelCapabilityProvenance;
  readonly contractType: string;
}

/** A durable product schema identity, kept outside the live capability lane. */
export interface ProductKernelSchemaDescriptor {
  readonly identity: string;
  readonly contractType: string;
}

/** An offline migration identity, never a Product Model capability target. */
export interface ProductKernelMigrationDescriptor {
  readonly identity: string;
  readonly from: string;
  readonly to: string;
  readonly contractType: string;
}

/** Exact source-linked JSON shape emitted by the Rust Product Kernel crate. */
export interface ProductKernelCatalogWire {
  readonly artifact: typeof PRODUCT_KERNEL_ARTIFACT;
  readonly schemas: readonly ProductKernelSchemaDescriptor[];
  readonly migrations: readonly ProductKernelMigrationDescriptor[];
  readonly capabilities: readonly ProductKernelCapabilityDescriptor[];
}

type CatalogEntry<Catalog extends ProductKernelCatalogWire> =
  Catalog['capabilities'][number];

type IsBaseCatalog<Catalog extends ProductKernelCatalogWire> =
  [Catalog] extends [ProductKernelCatalogWire]
    ? [ProductKernelCatalogWire] extends [Catalog] ? true : false
    : false;

type LinkableCatalogTarget<Catalog extends ProductKernelCatalogWire> =
  CatalogEntry<Catalog> extends infer Entry
    ? Entry extends { readonly availability: 'linkable'; readonly target: infer Target }
      ? Extract<Target, ProductKernelCapabilityTarget>
      : never
    : never;

/** The closed target union generated by a product's `as const` catalog. */
export type ProductKernelTarget<Catalog extends ProductKernelCatalogWire> =
  IsBaseCatalog<Catalog> extends true
    ? ProductKernelCapabilityTarget
    : LinkableCatalogTarget<Catalog>;

/** A catalog after strict validation and deep freezing. */
export type FrozenProductKernelCatalog<Catalog extends ProductKernelCatalogWire = ProductKernelCatalogWire> =
  Readonly<Catalog>;

/**
 * The product-local helpers bound to one immutable Product Kernel catalog.
 * The closure is an authoring convenience, never a runtime registry or invoke
 * surface: it only creates Product Model data and performs pre-start checks.
 */
export interface ProductKernelCatalogBinding<Catalog extends ProductKernelCatalogWire = ProductKernelCatalogWire> {
  readonly catalog: FrozenProductKernelCatalog<Catalog>;
  capability(id: string, target: ProductKernelTarget<Catalog>): CapabilityBinding;
  admit(draft: unknown): RuntimeCompositionArtifact;
  admitCompiled(value: unknown): CompiledComposition;
}

/**
 * Strictly admits the exact Rust Product Kernel JSON shape and returns only
 * detached, deeply frozen plain data. The catalog is versionless by design;
 * contract compatibility follows the actual fields emitted by Rust.
 */
export function createProductKernelCatalog<const Catalog extends ProductKernelCatalogWire>(
  value: Catalog,
): FrozenProductKernelCatalog<Catalog>;
export function createProductKernelCatalog(value: unknown): FrozenProductKernelCatalog;
export function createProductKernelCatalog(value: unknown): FrozenProductKernelCatalog {
  const root = catalogRecord(value, '$');
  exactKeys(root, ['artifact', 'schemas', 'migrations', 'capabilities'], '$');
  if (root['artifact'] !== PRODUCT_KERNEL_ARTIFACT) {
    catalogFail('product-kernel-catalog-invalid', '$.artifact', 'Product Kernel catalog artifact must be product-kernel');
  }
  const schemas = admitSchemas(root['schemas']);
  const migrations = admitMigrations(root['migrations'], new Set(schemas.map((entry) => entry.identity)));
  const capabilities = catalogArray(root['capabilities'], '$.capabilities');
  if (capabilities.length === 0) {
    catalogFail('product-kernel-catalog-invalid', '$.capabilities', 'Product Kernel catalog must contain at least one capability');
  }
  if (capabilities.length > MAX_CAPABILITY_BINDINGS) {
    catalogFail('product-kernel-catalog-invalid', '$.capabilities', `Product Kernel catalog exceeds ${String(MAX_CAPABILITY_BINDINGS)} capabilities`);
  }

  const entries: ProductKernelCapabilityDescriptor[] = [];
  let previousTarget: string | undefined;
  const identities = new Set<string>();
  const targets = new Set<string>();
  for (let index = 0; index < capabilities.length; index += 1) {
    const path = `$.capabilities[${String(index)}]`;
    const source = catalogRecord(capabilities[index], path);
    const entry = admitDescriptor(source, path);
    if (identities.has(entry.identity)) {
      catalogFail('product-kernel-catalog-invalid', `${path}.identity`, `duplicate Product Kernel identity ${entry.identity}`);
    }
    identities.add(entry.identity);
    if (targets.has(entry.target)) {
      catalogFail('product-kernel-catalog-invalid', `${path}.target`, `duplicate Product Kernel target ${entry.target}`);
    }
    targets.add(entry.target);
    if (previousTarget !== undefined && compareUtf8(previousTarget, entry.target) >= 0) {
      catalogFail(
        'product-kernel-catalog-unsorted',
        `${path}.target`,
        'Product Kernel capabilities must be strictly sorted by target',
      );
    }
    previousTarget = entry.target;
    entries.push(entry);
  }

  return Object.freeze({
    artifact: PRODUCT_KERNEL_ARTIFACT,
    schemas: Object.freeze(schemas),
    migrations: Object.freeze(migrations),
    capabilities: Object.freeze(entries),
  }) as FrozenProductKernelCatalog;
}

/**
 * Binds the strict catalog to the two source-authoring operations needed by a
 * generated downstream module. Re-validating here makes passing a hand-built
 * or stale object to the boundary safe as well.
 *
 * A Rust-generated product module can keep its source-linked artifact local:
 *
 * ```ts
 * const catalog = createProductKernelCatalog(generatedProductKernelCatalog);
 * export const ProductKernel = bindProductKernelCatalog(catalog);
 * export const capability = ProductKernel.capability;
 * export const admit = ProductKernel.admit;
 * ```
 *
 * The generated artifact is product-owned data; it does not belong in the
 * provider's global `generated.ts` Engine catalog.
 */
export function bindProductKernelCatalog<const Catalog extends ProductKernelCatalogWire>(
  value: Catalog,
): ProductKernelCatalogBinding<Catalog>;
export function bindProductKernelCatalog(value: unknown): ProductKernelCatalogBinding;
export function bindProductKernelCatalog(value: unknown): ProductKernelCatalogBinding {
  const catalog = createProductKernelCatalog(value);
  const targets = new Set(
    catalog.capabilities
      .filter((entry) => entry.availability === 'linkable')
      .map((entry) => entry.target),
  );

  const bound = {
    catalog,
    capability(id: string, target: ProductKernelCapabilityTarget): CapabilityBinding {
      if (!targets.has(target)) {
        catalogFail(
          'unknown-product-kernel-capability',
          '$.capability.target',
          `Product Kernel capability target ${target} is not present in the bound catalog`,
        );
      }
      return Object.freeze({ id: checkedIdentity(id, '$.capability.id'), target });
    },
    admit(draft: unknown): RuntimeCompositionArtifact {
      const artifact = authorRuntimeComposition(draft);
      assertCatalogBindings(artifact.composition, targets);
      return artifact;
    },
    admitCompiled(valueToAdmit: unknown): CompiledComposition {
      const composition = admitCompiledComposition(valueToAdmit);
      assertCatalogBindings(composition, targets);
      return composition;
    },
  } satisfies ProductKernelCatalogBinding;
  return Object.freeze(bound);
}

/** Target-union-typed capability creation for generated downstream modules. */
export function capability<Catalog extends ProductKernelCatalogWire>(
  catalog: FrozenProductKernelCatalog<Catalog>,
  id: string,
  target: ProductKernelTarget<Catalog>,
): CapabilityBinding {
  return bindProductKernelCatalog(catalog).capability(id, target);
}

/** Explicitly named alias for callers that prefer the provider vocabulary. */
export const productKernelCapability = capability;

/** Catalog-bound composition admission before Rust Product Assembly linkage. */
export function admitProductKernelComposition<Catalog extends ProductKernelCatalogWire>(
  catalog: FrozenProductKernelCatalog<Catalog>,
  draft: unknown,
): RuntimeCompositionArtifact {
  return bindProductKernelCatalog(catalog).admit(draft);
}

/** Alias matching the authoring vocabulary used by generated product modules. */
export const authorProductKernelComposition = admitProductKernelComposition;

function admitDescriptor(
  source: Readonly<Record<string, unknown>>,
  path: string,
): ProductKernelCapabilityDescriptor {
  exactKeys(source, [
    'identity', 'target', 'kind', 'uses', 'availability', 'access', 'budget', 'provenance', 'contractType',
  ], path);
  const identity = checkedIdentity(requiredFieldString(source, 'identity', path), `${path}.identity`);
  const target = requiredFieldString(source, 'target', path);
  if (target !== `kernel.${identity}`) {
    catalogFail(
      'product-kernel-catalog-stale',
      `${path}.target`,
      `target ${target} does not match the source identity ${identity}`,
    );
  }
  if (!target.startsWith('kernel.')) {
    catalogFail('product-kernel-catalog-invalid', `${path}.target`, 'Product Kernel targets must use the kernel. namespace');
  }
  const kind = listedString(source, 'kind', path, ['system', 'operation', 'query', 'projection']) as ProductKernelCapabilityKind;
  const uses = admittedUses(source['uses'], `${path}.uses`);
  if (uses.length === 0) {
    catalogFail('product-kernel-catalog-invalid', `${path}.uses`, 'a capability must declare at least one composition use');
  }
  const availability = listedString(source, 'availability', path, ['linkable', 'unavailable']) as 'linkable' | 'unavailable';
  const accessSource = catalogRecord(required(source, 'access', path), `${path}.access`);
  exactKeys(accessSource, ['reads', 'writes'], `${path}.access`);
  const access = Object.freeze({
    reads: admittedIdentities(accessSource['reads'], `${path}.access.reads`),
    writes: admittedIdentities(accessSource['writes'], `${path}.access.writes`),
  });
  const budgetSource = catalogRecord(required(source, 'budget', path), `${path}.budget`);
  exactKeys(budgetSource, ['maximumCompactJsonPayloadBytes'], `${path}.budget`);
  const budget = requiredPositiveInteger(
    budgetSource['maximumCompactJsonPayloadBytes'],
    `${path}.budget.maximumCompactJsonPayloadBytes`,
  );
  if (budget > MAX_COMPILED_COMPOSITION_BYTES) {
    catalogFail('product-kernel-catalog-invalid', `${path}.budget.maximumCompactJsonPayloadBytes`, 'capability payload budget exceeds the Product Model artifact limit');
  }
  const provenanceSource = catalogRecord(required(source, 'provenance', path), `${path}.provenance`);
  exactKeys(provenanceSource, ['owner', 'source', 'logicalPath'], `${path}.provenance`);
  const provenance = Object.freeze({
    owner: boundedText(requiredFieldString(provenanceSource, 'owner', `${path}.provenance`), `${path}.provenance.owner`),
    source: boundedText(requiredFieldString(provenanceSource, 'source', `${path}.provenance`), `${path}.provenance.source`),
    logicalPath: boundedText(requiredFieldString(provenanceSource, 'logicalPath', `${path}.provenance`), `${path}.provenance.logicalPath`),
  });
  const contractType = boundedText(requiredFieldString(source, 'contractType', path), `${path}.contractType`);
  return Object.freeze({
    identity,
    target: target as ProductKernelCapabilityTarget,
    kind,
    uses: Object.freeze(uses),
    availability,
    access,
    budget: Object.freeze({ maximumCompactJsonPayloadBytes: budget }),
    provenance,
    contractType,
  });
}

function admitSchemas(value: unknown): readonly ProductKernelSchemaDescriptor[] {
  const values = catalogArray(value, '$.schemas');
  if (values.length > MAX_CAPABILITY_BINDINGS) {
    catalogFail('product-kernel-catalog-invalid', '$.schemas', `Product Kernel schemas exceed ${String(MAX_CAPABILITY_BINDINGS)} entries`);
  }
  const output: ProductKernelSchemaDescriptor[] = [];
  const identities = new Set<string>();
  let previous: string | undefined;
  for (let index = 0; index < values.length; index += 1) {
    const path = `$.schemas[${String(index)}]`;
    const source = catalogRecord(values[index], path);
    exactKeys(source, ['identity', 'contractType'], path);
    const identity = checkedIdentity(requiredFieldString(source, 'identity', path), `${path}.identity`);
    const contractType = boundedText(requiredFieldString(source, 'contractType', path), `${path}.contractType`);
    if (contractType !== identity) {
      catalogFail('product-kernel-catalog-stale', `${path}.contractType`, `schema contractType ${contractType} does not match identity ${identity}`);
    }
    if (identities.has(identity)) {
      catalogFail('product-kernel-catalog-invalid', `${path}.identity`, `duplicate Product Kernel schema ${identity}`);
    }
    identities.add(identity);
    if (previous !== undefined && compareUtf8(previous, identity) >= 0) {
      catalogFail('product-kernel-catalog-unsorted', `${path}.identity`, 'Product Kernel schemas must be strictly sorted by identity');
    }
    previous = identity;
    output.push(Object.freeze({ identity, contractType }));
  }
  return output;
}

function admitMigrations(value: unknown, schemas: ReadonlySet<string>): readonly ProductKernelMigrationDescriptor[] {
  const values = catalogArray(value, '$.migrations');
  if (values.length > MAX_CAPABILITY_BINDINGS) {
    catalogFail('product-kernel-catalog-invalid', '$.migrations', `Product Kernel migrations exceed ${String(MAX_CAPABILITY_BINDINGS)} entries`);
  }
  const output: ProductKernelMigrationDescriptor[] = [];
  const identities = new Set<string>();
  let previous: string | undefined;
  for (let index = 0; index < values.length; index += 1) {
    const path = `$.migrations[${String(index)}]`;
    const source = catalogRecord(values[index], path);
    exactKeys(source, ['identity', 'from', 'to', 'contractType'], path);
    const identity = checkedIdentity(requiredFieldString(source, 'identity', path), `${path}.identity`);
    const from = checkedIdentity(requiredFieldString(source, 'from', path), `${path}.from`);
    const to = checkedIdentity(requiredFieldString(source, 'to', path), `${path}.to`);
    const contractType = boundedText(requiredFieldString(source, 'contractType', path), `${path}.contractType`);
    if (contractType !== identity) {
      catalogFail('product-kernel-catalog-stale', `${path}.contractType`, `migration contractType ${contractType} does not match identity ${identity}`);
    }
    if (!schemas.has(from) || !schemas.has(to)) {
      catalogFail('product-kernel-catalog-stale', path, 'migration schema endpoints must be present in the schemas catalog');
    }
    if (identities.has(identity)) {
      catalogFail('product-kernel-catalog-invalid', `${path}.identity`, `duplicate Product Kernel migration ${identity}`);
    }
    identities.add(identity);
    if (previous !== undefined && compareUtf8(previous, identity) >= 0) {
      catalogFail('product-kernel-catalog-unsorted', `${path}.identity`, 'Product Kernel migrations must be strictly sorted by identity');
    }
    previous = identity;
    output.push(Object.freeze({ identity, from, to, contractType }));
  }
  return output;
}

function admittedUses(value: unknown, path: string): readonly ProductKernelCapabilityUse[] {
  const values = catalogArray(value, path);
  const output: ProductKernelCapabilityUse[] = [];
  let previous: string | undefined;
  const seen = new Set<string>();
  for (let index = 0; index < values.length; index += 1) {
    const item = stringValue(values[index], `${path}[${String(index)}]`);
    if (item !== 'input-map' && item !== 'schedule' && item !== 'timeline') {
      catalogFail('product-kernel-catalog-invalid', `${path}[${String(index)}]`, `unknown Product Kernel composition use ${item}`);
    }
    if (seen.has(item)) {
      catalogFail('product-kernel-catalog-invalid', `${path}[${String(index)}]`, `duplicate Product Kernel composition use ${item}`);
    }
    if (previous !== undefined && compareUtf8(previous, item) >= 0) {
      catalogFail('product-kernel-catalog-unsorted', `${path}[${String(index)}]`, 'capability uses must be strictly sorted');
    }
    seen.add(item);
    previous = item;
    output.push(item);
  }
  return output;
}

function admittedIdentities(value: unknown, path: string): readonly string[] {
  const values = catalogArray(value, path);
  if (values.length > MAX_SCHEDULE_RESOURCE_DECLARATIONS) {
    catalogFail('product-kernel-catalog-invalid', path, `access declarations exceed ${String(MAX_SCHEDULE_RESOURCE_DECLARATIONS)} entries`);
  }
  const output: string[] = [];
  const seen = new Set<string>();
  for (let index = 0; index < values.length; index += 1) {
    const item = checkedIdentity(stringValue(values[index], `${path}[${String(index)}]`), `${path}[${String(index)}]`);
    if (seen.has(item)) {
      catalogFail('product-kernel-catalog-invalid', `${path}[${String(index)}]`, `duplicate access declaration ${item}`);
    }
    seen.add(item);
    output.push(item);
  }
  return Object.freeze(output);
}

function assertCatalogBindings(composition: CompiledComposition, targets: ReadonlySet<string>): void {
  for (const [index, binding] of composition.capabilityBindings.entries()) {
    if (binding.target.startsWith('kernel.') && !targets.has(binding.target)) {
      catalogFail(
        'unknown-product-kernel-capability',
        `$.capabilityBindings[${String(index)}].target`,
        `Product Kernel capability target ${binding.target} is not present in the bound catalog`,
      );
    }
  }
}

function exactKeys(source: Readonly<Record<string, unknown>>, expected: readonly string[], path: string): void {
  const actual = Object.keys(source).sort(compareUtf8);
  const wanted = [...expected].sort(compareUtf8);
  if (actual.length !== wanted.length || actual.some((key, index) => key !== wanted[index])) {
    catalogFail('product-kernel-catalog-invalid', path, `fields must be exactly ${expected.join(', ')}`);
  }
}

function catalogRecord(value: unknown, path: string): Readonly<Record<string, unknown>> {
  if (typeof value !== 'object' || value === null || Array.isArray(value)) {
    catalogFail('product-kernel-catalog-invalid', path, 'expected a plain object');
  }
  const prototype = Object.getPrototypeOf(value);
  if (prototype !== Object.prototype && prototype !== null) {
    catalogFail('product-kernel-catalog-invalid', path, 'catalog values must be plain data objects');
  }
  const descriptors = Object.getOwnPropertyDescriptors(value);
  for (const key of Reflect.ownKeys(descriptors)) {
    if (typeof key === 'symbol') {
      catalogFail('product-kernel-catalog-invalid', path, 'catalog objects cannot contain symbol keys');
    }
    const descriptor = descriptors[key];
    if (descriptor === undefined || !descriptor.enumerable || !('value' in descriptor)) {
      catalogFail('product-kernel-catalog-invalid', `${path}.${String(key)}`, 'catalog objects cannot contain accessors or non-enumerable fields');
    }
    if (descriptor.value === undefined) {
      catalogFail('product-kernel-catalog-invalid', `${path}.${String(key)}`, 'catalog objects cannot contain undefined fields');
    }
  }
  return value as Readonly<Record<string, unknown>>;
}

function catalogArray(value: unknown, path: string): readonly unknown[] {
  if (!Array.isArray(value) || Object.getPrototypeOf(value) !== Array.prototype) {
    catalogFail('product-kernel-catalog-invalid', path, 'catalog arrays must use the ordinary Array prototype');
  }
  for (let index = 0; index < value.length; index += 1) {
    if (!Object.hasOwn(value, index)) {
      catalogFail('product-kernel-catalog-invalid', `${path}[${String(index)}]`, 'catalog arrays cannot contain holes');
    }
  }
  for (const key of Reflect.ownKeys(value)) {
    if (key === 'length') continue;
    if (typeof key === 'symbol' || !isArrayIndexKey(String(key))) {
      catalogFail('product-kernel-catalog-invalid', path, 'catalog arrays cannot contain non-index properties');
    }
    const descriptor = Object.getOwnPropertyDescriptor(value, key);
    if (descriptor === undefined || !descriptor.enumerable || !('value' in descriptor) || descriptor.value === undefined) {
      catalogFail('product-kernel-catalog-invalid', `${path}[${String(key)}]`, 'catalog arrays cannot contain accessors or undefined values');
    }
  }
  return value;
}

function isArrayIndexKey(key: string): boolean {
  if (key !== '0' && !/^[1-9][0-9]*$/.test(key)) return false;
  const numeric = Number(key);
  return Number.isSafeInteger(numeric) && numeric < 4_294_967_295 && String(numeric) === key;
}

function listedString(
  source: Readonly<Record<string, unknown>>,
  field: string,
  path: string,
  values: readonly string[],
): string {
  const value = requiredFieldString(source, field, path);
  if (!values.includes(value)) {
    catalogFail('product-kernel-catalog-invalid', `${path}.${field}`, `field ${field} is not in the closed Product Kernel vocabulary`);
  }
  return value;
}

function required(source: Readonly<Record<string, unknown>>, field: string, path: string): unknown {
  if (!Object.hasOwn(source, field)) {
    catalogFail('product-kernel-catalog-invalid', `${path}.${field}`, `missing required field ${field}`);
  }
  return source[field];
}

function requiredFieldString(source: Readonly<Record<string, unknown>>, field: string, path: string): string {
  return stringValue(required(source, field, path), `${path}.${field}`);
}

function stringValue(value: unknown, path: string): string {
  if (typeof value !== 'string') {
    catalogFail('product-kernel-catalog-invalid', path, 'expected a string');
  }
  return value;
}

function checkedIdentity(value: string, path: string): string {
  const identity = /^[a-z0-9](?:[a-z0-9]|[._-](?=[a-z0-9]))*$/;
  if (utf8Length(value) > PRODUCT_MODEL_IDENTITY.maximumBytes || !identity.test(value)) {
    catalogFail('product-kernel-catalog-invalid', path, 'catalog identities must use the Product Model identity grammar');
  }
  return value;
}

function boundedText(value: string, path: string): string {
  if (value.length === 0 || utf8Length(value) > 512) {
    catalogFail('product-kernel-catalog-invalid', path, 'catalog provenance and contract text must contain 1..=512 UTF-8 bytes');
  }
  return value;
}

function requiredPositiveInteger(value: unknown, path: string): number {
  if (!Number.isSafeInteger(value) || (value as number) <= 0) {
    catalogFail('product-kernel-catalog-invalid', path, 'catalog budgets must be positive safe integers');
  }
  return value as number;
}

function catalogFail(
  code: 'product-kernel-catalog-invalid' | 'product-kernel-catalog-stale' | 'product-kernel-catalog-unsorted' | 'unknown-product-kernel-capability',
  path: string,
  message: string,
): never {
  throw new RuntimeCompositionAuthoringError(code, path, message);
}
