[package]
name = "product-dev-host"
version.workspace = true
edition.workspace = true

[dependencies]
render-model.workspace = true
render-host-contracts.workspace = true
render-presentation.workspace = true
runtime-lifecycle.workspace = true
runtime-input.workspace = true
runtime-session.workspace = true
runtime-timeline.workspace = true
runtime-ui.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true

[lints]
workspace = true
