[package]
name = "product-kernel"
version.workspace = true
edition.workspace = true

[dependencies]
product-model.workspace = true
runtime-lifecycle.workspace = true
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
runtime-mutation.workspace = true
runtime-schedule.workspace = true
runtime-standard-capabilities.workspace = true

[lints]
workspace = true
