[package]
name = "gameplay-mechanics"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
core-ids.workspace = true
entity-state.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true

[dev-dependencies]
stats_alloc.workspace = true
