[package]
name = "product-materializer"
version.workspace = true
edition.workspace = true

[dependencies]
cap-primitives.workspace = true
cap-std.workspace = true
product-assembly.workspace = true
product-model.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tempfile.workspace = true

[lints]
workspace = true
