// Generated by render/scripts/generate-product-ui-types.mjs from the Engine's
// browser sources; do not edit. Pass this file to a product UI's tsc to
// type `@rusty-engine/product-ui` and `@rusty-engine/live-debug`.
declare module "@rusty-engine/product-ui/internal/application-host/src/generated/contracts" {
    /** Where the page pulls the frames the runtime renders. */
    export const FRAME_STREAM_PATH = "/__rusty/product/runtime/frames";
    /** The little-endian `RSF1` frame header: its magic, field offsets, formats and flags. */
    export const FRAME_STREAM_HEADER: {
        readonly magic: 826692434;
        readonly offsets: {
            readonly headerBytes: 4;
            readonly sequence: 8;
            readonly step: 16;
            readonly width: 24;
            readonly height: 28;
            readonly format: 32;
            readonly flags: 33;
            readonly payloadBytes: 36;
        };
        readonly bytes: 40;
        readonly formats: {
            readonly jpeg: 1;
            readonly rgba8: 2;
        };
        readonly flags: {
            readonly held: 1;
            readonly video: 2;
        };
    };
    /** Where the page listens to the audio the runtime mixes. */
    export const AUDIO_STREAM_PATH = "/__rusty/product/runtime/audio";
    /** The streamed audio: interleaved signed 16-bit little-endian PCM. */
    export const AUDIO_STREAM_FORMAT: {
        readonly sampleRate: 48000;
        readonly channels: 2;
    };
    /** Where the page reports how it presents the product. */
    export const PRESENTATION_PATH = "/__rusty/product/runtime/presentation";
    export type ControllerAxis = "axis-0" | "axis-1" | "axis-2" | "axis-3";
    export type ControllerButton = "button-0" | "button-1" | "button-2" | "button-3" | "button-4" | "button-5" | "button-6" | "button-7" | "button-8" | "button-9" | "button-10" | "button-11" | "button-12" | "button-13" | "button-14" | "button-15";
    export type JsonValue = number | string | boolean | Array<JsonValue> | {
        [key in string]?: JsonValue;
    } | null;
    export type KeyboardControl = "key-a" | "key-b" | "key-c" | "key-d" | "key-e" | "key-f" | "key-g" | "key-h" | "key-i" | "key-j" | "key-k" | "key-l" | "key-m" | "key-n" | "key-o" | "key-p" | "key-q" | "key-r" | "key-s" | "key-t" | "key-u" | "key-v" | "key-w" | "key-x" | "key-y" | "key-z" | "digit-0" | "digit-1" | "digit-2" | "digit-3" | "digit-4" | "digit-5" | "digit-6" | "digit-7" | "digit-8" | "digit-9" | "space" | "enter" | "escape" | "shift-left" | "shift-right" | "control-left" | "control-right" | "alt-left" | "alt-right" | "arrow-up" | "arrow-down" | "arrow-left" | "arrow-right";
    export type PointerButton = "primary" | "secondary" | "middle";
    /**
     * How gameplay holds the pointer.
     */
    export type ProductHostCursorMode = "pointer-lock" | "unlocked";
    /**
     * What the page reports about its presentation.
     */
    export type ProductHostPresentationReport = {
        cssWidth: number;
        cssHeight: number;
        devicePixelRatio: number;
        uiScale: number;
        anchors: Array<ProductHostViewportAnchorReport>;
    };
    /**
     * Where the runtime presents the frames it renders.
     */
    export type ProductHostRenderOutput = "stream" | "window";
    /**
     * One anchored element's rect, normalized to the presentation surface,
     * bottom-left based.
     */
    export type ProductHostViewportAnchorReport = {
        name: string;
        x: number;
        y: number;
        width: number;
        height: number;
    };
    /**
     * The runtime binding an envelope belongs to, as canonical decimal text.
     */
    export type RuntimeInputWireBinding = {
        instanceId: string;
        generation: string;
        controlRevision: string;
    };
    /**
     * Why a host cleared held input.
     */
    export type RuntimeInputWireClearReason = "focus-loss" | "interaction-mode-loss" | "pointer-lock-loss" | "restart" | "control-revision-change" | "dispose" | "ingress-overflow";
    export type RuntimeInputWireEdge = "pressed" | "released";
    /**
     * One input envelope a host submits, in observation order: a physical fact
     * or an intent claimed by product UI.
     */
    export type RuntimeInputWireEvent = RuntimeInputWirePhysical | RuntimeInputWireIntentClaim;
    /**
     * A physical fact from the closed Engine input catalog.
     */
    export type RuntimeInputWireFact = {
        "kind": "key";
        code: KeyboardControl;
        edge: RuntimeInputWireEdge;
    } | {
        "kind": "pointer-button";
        button: PointerButton;
        edge: RuntimeInputWireEdge;
        position?: RuntimeInputWirePointerPosition;
    } | {
        "kind": "pointer-delta";
        x: number;
        y: number;
    } | {
        "kind": "pointer-position";
        x: number;
        y: number;
    } | {
        "kind": "wheel";
        x: number;
        y: number;
    } | {
        "kind": "controller-button";
        button: ControllerButton;
        edge: RuntimeInputWireEdge;
    } | {
        "kind": "controller-axis";
        axis: ControllerAxis;
        value: number;
    } | {
        "kind": "controller-button-value";
        button: ControllerButton;
        value: number;
    } | {
        "kind": "clear";
        reason: RuntimeInputWireClearReason;
    };
    /**
     * A product-declared intent claimed by product UI, in the same ordered lane.
     */
    export type RuntimeInputWireIntentClaim = {
        runtime: RuntimeInputWireBinding;
        /**
         * Canonical decimal u64, increasing within the binding.
         */
        sequence: string;
        /**
         * Product-declared input context.
         */
        context: string;
        /**
         * Product-declared intent name.
         */
        intent: string;
        value: RuntimeInputWireIntentValue;
    };
    export type RuntimeInputWireIntentValue = {
        "kind": "digital";
        active: boolean;
    } | {
        "kind": "axis";
        value: number;
    } | {
        "kind": "product-payload";
        contract: string;
        data: JsonValue;
    };
    /**
     * A physical input fact observed for one runtime binding.
     */
    export type RuntimeInputWirePhysical = {
        runtime: RuntimeInputWireBinding;
        /**
         * Canonical decimal u64, increasing within the binding.
         */
        sequence: string;
        /**
         * Product-declared input context.
         */
        context: string;
        fact: RuntimeInputWireFact;
    };
    /**
     * A cursor position on the presentation surface, normalized and
     * bottom-left based like a camera viewport.
     */
    export type RuntimeInputWirePointerPosition = {
        x: number;
        y: number;
    };
    /**
     * The wire shape of a UI projection envelope: what the browser host
     * receives and passes to the mounted product UI.
     */
    export type RuntimeUiProjectionEnvelope = {
        artifact: "rusty.product.ui-projection";
        runtime: RuntimeUiRuntimeWire;
        /**
         * Canonical decimal u64, increasing within the runtime binding.
         */
        sequence: string;
        stream: string;
        /**
         * The product's projection contract identity.
         */
        contract: string;
        /**
         * The product-owned projection value.
         */
        value: JsonValue;
    };
    /**
     * The runtime binding a projection belongs to, as canonical decimal text.
     */
    export type RuntimeUiRuntimeWire = {
        instanceId: string;
        generation: string;
        controlRevision: string;
    };
}
declare module "@rusty-engine/product-ui" {
    /**
     * What a product UI module sees: the mount signature and the context ports
     * the Engine passes it. Types only, depending on nothing but the generated
     * wire contracts, so the SDK can ship them as `@rusty-engine/product-ui` for
     * product UIs to compile against.
     */
    import type { RuntimeInputWireFact, RuntimeInputWireIntentValue, RuntimeUiProjectionEnvelope } from "@rusty-engine/product-ui/internal/application-host/src/generated/contracts";
    export type { JsonValue, RuntimeInputWireIntentValue, RuntimeUiProjectionEnvelope, } from "@rusty-engine/product-ui/internal/application-host/src/generated/contracts";
    export type RustyApplicationInteractionMode = 'gameplay' | 'interface' | 'modal';
    export interface RustyApplicationUiPort {
        readonly active: () => boolean;
        /**
         * Classify one original host event before a downstream adapter gives it
         * gameplay meaning. Interactive UI is rejected synchronously even before a
         * later click handler changes the coarse interaction mode.
         */
        readonly allowsGameplayInput: (event: Event) => boolean;
        readonly focusGameplay: () => void;
        readonly interactionMode: () => RustyApplicationInteractionMode;
        readonly setInteractionMode: (mode: RustyApplicationInteractionMode) => void;
        /** The gameplay cursor mode now: the product's declared mode until set. */
        readonly cursorMode: () => 'pointer-lock' | 'unlocked';
        /**
         * Switch the gameplay cursor at run time, for a map or strategy screen in a
         * mouselook product. `'unlocked'` releases pointer lock and keeps clicks
         * from taking it again; clicks and pointer movement then carry the cursor
         * position. `'pointer-lock'` takes the lock again on the next click.
         */
        readonly setCursorMode: (mode: 'pointer-lock' | 'unlocked') => void;
        /** The UI scale; 1 until set. The product reads it as `CameraView.ReadSurface().UiScale`. */
        readonly scale: () => number;
        /**
         * Set the UI scale (finite, 0.25 to 4), as a player's UI-scale setting: the
         * document root's font size and its `--rusty-ui-scale` property follow it,
         * so rem-sized UI scales.
         */
        readonly setScale: (scale: number) => void;
    }
    /**
     * Ties camera views to UI elements. A camera the product anchors under
     * `name` (`CameraView.SetViewportAnchor`) draws its primary views over the
     * element anchored under the same name, following it on resize and layout
     * change with no product code running.
     */
    export interface RustyApplicationUiViewportPort {
        /** Anchor `name` to `element`; returns a function that removes the anchor. */
        readonly anchor: (name: string, element: Element) => () => void;
    }
    /**
     * A claim's value: a digital or axis value, or a product payload. A
     * payload's data is the product's own JSON value, typed by the product.
     */
    export type RustyApplicationUiIntentValue = Exclude<RuntimeInputWireIntentValue, {
        readonly kind: 'product-payload';
    }> | {
        readonly kind: 'product-payload';
        readonly contract: string;
        readonly data: unknown;
    };
    /**
     * Mounted DOM UI can emit a claim, but cannot drain or bind the input lane.
     * A claim made while the runtime is paused reaches the product's
     * `HandlePausedIntents` once instead of `Update`.
     */
    export interface RustyApplicationUiIntentsPort {
        readonly claim: (intent: string, value: RustyApplicationUiIntentValue) => void;
    }
    /** The Engine runtime's lifecycle state, as its readout reports it. */
    export type RustyApplicationRuntimeState = 'created' | 'running' | 'paused' | 'faulted' | 'shutdown';
    /** The Engine's answer to one pause or resume request. */
    export interface RustyApplicationUiLifecycleResult {
        readonly accepted: boolean;
        /** The runtime state after the request, as last reported by the Engine. */
        readonly state: RustyApplicationRuntimeState | null;
        /** The Engine's rejection code, such as a request for a replaced runtime or the wrong state. */
        readonly code?: string;
        readonly diagnostic?: string;
    }
    /**
     * Pauses and resumes the Engine runtime. Pause stops simulation admission and
     * clears held and pending gameplay input; resume continues in the same
     * runtime without replaying paused wall time or input. State follows the
     * Engine, so a pause from elsewhere (a tool or another page) is observed too.
     */
    export interface RustyApplicationUiLifecyclePort {
        /** The last reported runtime state, or null before the first report. */
        readonly state: () => RustyApplicationRuntimeState | null;
        /** Subscribe to state changes; returns an unsubscribe function. */
        readonly subscribe: (listener: (state: RustyApplicationRuntimeState | null) => void) => () => void;
        /**
         * Request a pause of the current runtime. Rejects when the host has failed
         * or is disposed, or the request's outcome is unknown.
         */
        readonly pause: () => Promise<RustyApplicationUiLifecycleResult>;
        /** Request a resume of the current runtime; rejects as `pause` does. */
        readonly resume: () => Promise<RustyApplicationUiLifecycleResult>;
    }
    export interface RustyApplicationUiContext {
        readonly ui: RustyApplicationUiPort;
        /** Engine runtime pause and resume, present when a runtime host mounts the UI. */
        readonly lifecycle?: RustyApplicationUiLifecyclePort;
        /** Read-only current Product UI projection and subscription view. */
        readonly projection?: RustyApplicationUiProjectionView;
        /** Claim-only adapter for the shared ordered Engine input lane. */
        readonly intents?: RustyApplicationUiIntentsPort;
        /** Read-only controller observations owned exclusively by interface mode. */
        readonly input?: RustyApplicationUiInputPort;
        /** Camera views that follow UI elements. */
        readonly viewport: RustyApplicationUiViewportPort;
    }
    export interface RustyApplicationUiInputPort {
        /** Synchronous observation on the host cadence; returns an unsubscribe function. */
        readonly subscribe: (observer: (input: RustyApplicationInterfaceInputObservation) => void) => () => void;
    }
    export interface RustyApplicationUiOwner {
        readonly dispose: () => void | Promise<void>;
    }
    /**
     * Mount trusted downstream product UI into the Engine-owned composition root.
     * This is an application composition seam, not an untrusted plugin boundary.
     * The root is hit-test transparent: native interactive controls and descendants
     * marked `data-rusty-ui-interactive` receive pointer events, while other overlay
     * regions pass through to the Engine canvas and its input arbitration.
     */
    export type RustyApplicationUiMount = (root: HTMLElement, context: RustyApplicationUiContext) => void | RustyApplicationUiOwner | Promise<void | RustyApplicationUiOwner>;
    /** UI-owned observations from the existing selected-controller sampler. */
    export interface RustyApplicationInterfaceInputObservation {
        readonly context: 'interface';
        readonly fact: Extract<RuntimeInputWireFact, {
            readonly kind: 'controller-button' | 'controller-axis' | 'controller-button-value';
        }>;
    }
    export interface RustyApplicationUiProjectionView {
        /** Returns the current immutable envelope, or null before the first value. */
        readonly current: () => RuntimeUiProjectionEnvelope | null;
        /** Subscribe to the current value. Rebinding publishes null before later values. */
        readonly subscribe: (listener: (value: RuntimeUiProjectionEnvelope | null) => void) => () => void;
    }
}
declare module "@rusty-engine/live-debug/internal/live-debug-client/src/generated/contracts" {
    /**
     * A JSON u64 represented as canonical decimal text.
     */
    export type CanonicalU64 = string;
    export type ProductHostAmbientOcclusionPath = "off" | "compute" | "raster" | "distanceField";
    /**
     * The screen-space ambient occlusion of the last world view.
     */
    export type ProductHostAmbientOcclusionStatistics = {
        path: ProductHostAmbientOcclusionPath;
        /**
         * Why the compute path cannot run on this device; absent while it can.
         */
        computeRefused?: string;
        /**
         * Workgroups the last occlusion dispatch took; 0 on the raster path.
         */
        workgroups: number;
        /**
         * The occlusion texture of the last view, in texels.
         */
        texture: [number, number];
    };
    /**
     * The adapter's compute limits; the renderer's device takes wgpu's defaults.
     */
    export type ProductHostComputeLimits = {
        workgroupSize: [number, number, number];
        invocationsPerWorkgroup: number;
        workgroupsPerDimension: number;
        workgroupStorageBytes: number;
        storageBufferBindingBytes: number;
    };
    /**
     * Read-only product-generated descriptor data for live-debug completion and
     * help. It is never a dispatch schema: command invocation remains the single
     * explicit `execute_debug` operation.
     */
    export type ProductHostDebugCatalog = {
        available: boolean;
        commands: Array<ProductHostDebugCommandDescriptor>;
    };
    export type ProductHostDebugCommandDescriptor = {
        name: string;
        description: string;
        parameters: Array<ProductHostDebugCommandParameterDescriptor>;
    };
    export type ProductHostDebugCommandParameterDescriptor = {
        name: string;
        type: string;
    };
    /**
     * `diagnostics/read`: diagnostics after a cursor, or the retained ones.
     */
    export type ProductHostDiagnosticsReadRequest = {
        after?: CanonicalU64;
    };
    /**
     * The `diagnostics/read` answer: retained diagnostics and host telemetry.
     */
    export type ProductHostDiagnosticsReadResponse = {
        telemetry: ProductHostTelemetrySnapshot;
        events: Array<RuntimeDiagnosticEvent>;
        floorSequence: CanonicalU64;
        throughSequence: CanonicalU64;
        nextCursor: CanonicalU64;
        readMonotonicNanoseconds: CanonicalU64;
        lagged: boolean;
        warningCount: CanonicalU64;
        errorCount: CanonicalU64;
        droppedCount: CanonicalU64;
    };
    /**
     * The chunk distance field atlas the `distanceField` ambient occlusion
     * path cone-traces.
     */
    export type ProductHostDistanceFieldStatistics = {
        /**
         * Why this device cannot trace the fields; absent while it can.
         */
        refused?: string;
        /**
         * Chunk fields resident in the atlas.
         */
        residentFields: number;
        /**
         * Bricks the atlas holds room for.
         */
        atlasBricks: number;
        atlasBytes: bigint;
        /**
         * Fields placed around the camera for the last world view.
         */
        lookupEntries: number;
    };
    export type ProductHostErrorBody = {
        code: string;
        diagnostic: string;
    };
    /**
     * The body of every host error response.
     */
    export type ProductHostErrorResponse = {
        accepted: false;
        error: ProductHostErrorBody;
    };
    /**
     * The GPU visibility of the last view pass.
     */
    export type ProductHostGpuCullingStatistics = {
        /**
         * The last view pass drew its opaque batches from GPU-culled runs.
         */
        enabled: boolean;
        /**
         * Why this device cannot cull on the GPU; absent while it can.
         */
        refused?: string;
        /**
         * Opaque candidates the last pass tested.
         */
        candidates: number;
        /**
         * Opaque batches the last pass drew indirectly.
         */
        batches: number;
        /**
         * Instances the last read-back pass found visible.
         */
        visible: number;
        /**
         * Runs of batches drawn with one multi-draw each.
         */
        multiDraws: number;
    };
    /**
     * One timed pass's GPU cost over the recent frames.
     */
    export type ProductHostGpuPass = {
        pass: string;
        /**
         * Recent frames whose GPU time was read back.
         */
        timedFrames: number;
        /**
         * Median GPU milliseconds of the pass over those frames; 0 with none.
         */
        medianGpuMs: number;
    };
    /**
     * What the renderer's GPU passes cost, from the device's timestamp
     * queries, with the adapter's compute limits.
     */
    export type ProductHostGpuStatistics = {
        /**
         * The device has timestamp queries, so the passes are timed.
         */
        timestamps: boolean;
        limits: ProductHostComputeLimits;
        /**
         * The timed passes, in frame order.
         */
        passes: Array<ProductHostGpuPass>;
        ambientOcclusion: ProductHostAmbientOcclusionStatistics;
        distanceFields: ProductHostDistanceFieldStatistics;
        lightClusters: ProductHostLightClusterStatistics;
        gpuCulling: ProductHostGpuCullingStatistics;
        indirectLight: ProductHostIndirectLightStatistics;
    };
    /**
     * The indirect light volume (`CameraView.SetIndirectLight`): its probes and
     * the bake that keeps them current.
     */
    export type ProductHostIndirectLightStatistics = {
        /**
         * A volume is requested.
         */
        enabled: boolean;
        /**
         * Probes per axis of the baked volume (zeros before the first bake).
         */
        dims: [number, number, number];
        probes: number;
        /**
         * Probes inside geometry, filled from their neighbours.
         */
        invalid: number;
        /**
         * Triangles in the bricks' and the outside's BVHs.
         */
        triangles: number;
        /**
         * The last batch's wall time in milliseconds, collection included.
         */
        bakeMs: number;
        /**
         * Batches of bricks baked since the renderer was made.
         */
        bakes: number;
        /**
         * A change waits for the debounce, or bricks are dirty or baking.
         */
        pending: boolean;
        /**
         * GPU bytes the volume's texture holds.
         */
        bytes: bigint;
        /**
         * 16 m bricks the volume is kept in.
         */
        bricks: number;
        /**
         * Bricks dirty or baking.
         */
        bricksPending: number;
        /**
         * The last brick's bake wall milliseconds.
         */
        brickMs: number;
        /**
         * The slowest brick since the renderer was made, in milliseconds.
         */
        brickMsMax: number;
        /**
         * Bytes the last frame that uploaded bricks wrote to the texture.
         */
        uploadBytes: bigint;
        /**
         * Bricks the last batch baked.
         */
        lastBatchBricks: number;
    };
    /**
     * The light clustering of the last world view.
     */
    export type ProductHostLightClusterStatistics = {
        /**
         * The last world view's lighting read its clusters.
         */
        enabled: boolean;
        /**
         * Why this device cannot cluster; absent while it can.
         */
        refused?: string;
        /**
         * Why the last world view looped although clustering is on: more
         * unbounded lights than the global list names. Absent while it
         * clustered.
         */
        fallback?: string;
        /**
         * Tiles across, tiles down, depth slices.
         */
        grid: [number, number, number];
        /**
         * Lights each cluster can hold.
         */
        clusterCapacity: number;
        /**
         * Light rows the last binning placed in clusters, counted per cluster.
         */
        binnedLights: number;
        /**
         * Lights every fragment sees: ambient, hemisphere, directional, and
         * point or spot lights without a range.
         */
        globalLights: number;
        /**
         * Clusters that had more lights than they hold.
         */
        overflowedClusters: number;
    };
    /**
     * Closed operation identities returned by direct runtime calls.
     */
    export type ProductHostOperationKind = "connect" | "start" | "pause" | "resume" | "restart" | "shutdown" | "report-fault" | "replace-control" | "release-control" | "claim-control" | "input" | "advance-realtime" | "complete-timeline" | "execute-debug";
    /**
     * Where the runtime presents the frames it renders.
     */
    export type ProductHostRenderOutput = "stream" | "window";
    export type ProductHostRendererSettingValues = {
        shadows: boolean;
        shadowBudget: number | null;
        /**
         * `disabled`, `screenSpace` or `distanceField`.
         */
        ambientOcclusion: string;
        ambientOcclusionStrength: number;
        ambientOcclusionRadius: number;
        /**
         * Samples per pixel of the primary destination.
         */
        antialiasing: number;
        /**
         * The fraction of the primary destination's size the world draws at.
         */
        renderScale: number;
        vsync: boolean;
        clusteredLighting: boolean;
        gpuCulling: boolean;
    };
    /**
     * The renderer settings (`RendererSettings`): what the product or its
     * manifest asked for, what draws, and why each refused setting differs.
     */
    export type ProductHostRendererSettings = {
        requested: ProductHostRendererSettingValues;
        effective: ProductHostRendererSettingValues;
        /**
         * By setting name, why the device draws it differently.
         */
        refused: Record<string, string>;
    };
    /**
     * The runtime renderer's adapter and what its recent frames cost.
     */
    export type ProductHostRendererStatistics = {
        adapter: string;
        output: ProductHostRenderOutput;
        /**
         * The recent streamed frames; the desktop window streams nothing.
         */
        stream?: ProductHostStreamStatistics;
        /**
         * The recent frames the desktop window presented.
         */
        window?: ProductHostWindowStatistics;
        /**
         * When each recent product update that received input finished, and
         * the step it simulated: the first frame showing that step or a later
         * one is the first to show the input.
         */
        inputSteps: Array<ProductHostTimedStep>;
        /**
         * Retained operations the renderer skipped, by kind.
         */
        skippedOps: Record<string, number>;
        lastSkip: string | null;
        shadows: ProductHostShadowStatistics;
        /**
         * The renderer's GPU passes: each timed pass's cost, the adapter's
         * compute limits, and the ambient occlusion the last world view took.
         */
        gpu: ProductHostGpuStatistics;
        /**
         * The renderer settings in effect (`RendererSettings`).
         */
        settings: ProductHostRendererSettings;
    };
    /**
     * Answer to `engine.renderer`, `.status`, `.show`, `.hide` and `.toggle`.
     */
    export type ProductHostRendererStatus = {
        available: boolean;
        widget: ProductHostRendererWidget;
        /**
         * Why no renderer statistics are available.
         */
        diagnostic?: string;
        renderer?: ProductHostRendererStatistics;
    };
    /**
     * The renderer metrics widget every mounted live-debug panel shares.
     */
    export type ProductHostRendererWidget = {
        visible: boolean;
    };
    /**
     * Exact runtime generation binding used by browser input, operations, and outputs.
     */
    export type ProductHostRuntimeBinding = {
        instanceId: CanonicalU64;
        generation: CanonicalU64;
        controlRevision: CanonicalU64;
    };
    /**
     * The scene's shadow layers and which requesting lights cast.
     */
    export type ProductHostShadowStatistics = {
        /**
         * Layers in the shadow atlas, and the 2048² pages holding them.
         */
        layers: number;
        pages: number;
        /**
         * `RustyEngineProductShadowBudget` in layers, if the manifest sets one.
         */
        budget: number | null;
        /**
         * Lights casting, and the renderer handles of those requesting a
         * shadow that the budget left out.
         */
        castingLights: number;
        skippedLights: number[];
        /**
         * Layers re-rendered in the last frame and the casters drawn into them.
         */
        renderedLayers: number;
        renderedCasters: number;
    };
    /**
     * Median milliseconds per frame for each stage of streaming it.
     */
    export type ProductHostStreamMedians = {
        render: number;
        readback: number;
        encode: number;
    };
    /**
     * What the recent streamed frames cost.
     */
    export type ProductHostStreamStatistics = {
        /**
         * The size the most recent viewer asked for, in its pixels.
         */
        viewerSize: [number, number] | null;
        recentFrames: number;
        framesPerSecond: number;
        medianMs: ProductHostStreamMedians;
        medianBytesPerFrame: number;
        bytesPerSecond: number;
        /**
         * When each recent frame was published, and the step it showed.
         */
        shown: Array<ProductHostTimedStep>;
    };
    /**
     * Bounded host-owned product-lane telemetry returned alongside the existing
     * diagnostics batch. These are observations only; renderer statistics are
     * answered by `engine.renderer` and are not folded into this product-lane
     * snapshot.
     */
    export type ProductHostTelemetrySnapshot = {
        inFlightOperation: ProductHostOperationKind | null;
        inFlightAgeMs: CanonicalU64 | null;
        lastProductAdmissionLatencyMs: CanonicalU64 | null;
        lastInputAdmissionLatencyMs: CanonicalU64 | null;
        queuedInputBatches: number;
        queuedInputEvents: number;
        inputBatchCapacity: number;
        oldestInputAgeMs: CanonicalU64 | null;
        inputOverflowPending: boolean;
        /**
         * Progress rate in millihertz, retaining useful values below one update
         * per second without introducing floating point into the wire snapshot.
         */
        runtimeProgressRateMillihertz: CanonicalU64 | null;
        runtimeProgressAgeMs: CanonicalU64 | null;
        runtimeProgressUnavailableReason: string | null;
        connections: number;
        subscribers: number;
        outputQueueItems: number;
        outputQueueCapacity: number;
        outputBindingActive: boolean;
        /**
         * Bounded attribution for completed C# update callbacks. Service totals
         * are nested within the callback duration, not additional frame time.
         */
        updateAttribution: ProductHostUpdateAttributionSnapshot | null;
    };
    /**
     * A simulation step and when something happened to it, in Unix
     * milliseconds.
     */
    export type ProductHostTimedStep = {
        atUnixMs: number;
        step: number;
    };
    /**
     * One complete C# update callback observation. Durations are integer
     * microseconds so the diagnostics wire remains canonical and float-free.
     */
    export type ProductHostUpdateAttribution = {
        runtime: ProductHostRuntimeBinding | null;
        simulationStep: CanonicalU64;
        admittedStepCount: CanonicalU64;
        postCallbackDurationUs: CanonicalU64;
        callbackDurationUs: CanonicalU64;
        characterStepCalls: CanonicalU64;
        characterStepDurationUs: CanonicalU64;
        /**
         * Controller casts reported by character-step receipts; this is not a
         * low-level narrow-phase counter.
         */
        characterStepCastCount: CanonicalU64;
        /**
         * Projection entries admitted by conservative character-query bounds,
         * plus active obstacles that have no cached projection bound.
         */
        characterStepCandidateCount: CanonicalU64;
        /**
         * Actual Parry character cast/contact calls, nested within the logical
         * controller cast count and candidate count.
         */
        characterStepNarrowPhaseCount: CanonicalU64;
        voxelResidencyCalls: CanonicalU64;
        voxelResidencyDurationUs: CanonicalU64;
        voxelScenePresentationCalls: CanonicalU64;
        voxelScenePresentationDurationUs: CanonicalU64;
    };
    /**
     * Host-owned rolling distribution and long-lived slowest complete update.
     */
    export type ProductHostUpdateAttributionSnapshot = {
        sampleCount: CanonicalU64;
        callbackDurationUsP50: CanonicalU64;
        callbackDurationUsP95: CanonicalU64;
        callbackDurationUsMax: CanonicalU64;
        latest: ProductHostUpdateAttribution;
        /**
         * Slowest complete callback retained in the current rolling window.
         */
        rollingSlowest: ProductHostUpdateAttribution;
        rollingSlowestAgeMs: CanonicalU64;
        /**
         * Slowest complete callback observed for this host lifetime.
         */
        slowest: ProductHostUpdateAttribution;
        slowestAgeMs: CanonicalU64;
    };
    /**
     * Median milliseconds per frame for each stage of presenting it: waiting
     * for the swapchain image, waiting for the scene, encoding and submitting
     * the frame, and presenting it.
     */
    export type ProductHostWindowMedians = {
        acquire: number;
        lock: number;
        draw: number;
        present: number;
    };
    /**
     * What the recent frames the desktop window presented cost, and when they
     * reached it.
     */
    export type ProductHostWindowStatistics = {
        recentFrames: number;
        framesPerSecond: number;
        medianMs: ProductHostWindowMedians;
        /**
         * When each recent frame was presented, and the step it showed.
         */
        shown: Array<ProductHostTimedStep>;
        /**
         * When recent key and mouse button events reached the window, in Unix
         * milliseconds.
         */
        inputsReceivedAtUnixMs: Array<number>;
    };
    export type RuntimeDiagnosticDisposition = "accepted" | "rejected-recoverable" | "degraded" | "resync-required" | "terminal";
    export type RuntimeDiagnosticEvent = {
        sequence: CanonicalU64;
        monotonicNanoseconds: CanonicalU64;
        severity: RuntimeDiagnosticSeverity;
        disposition: RuntimeDiagnosticDisposition;
        source: string;
        code: string;
        message: string;
        runtime?: RuntimeDiagnosticRuntimeBinding;
        correlation?: string;
        fields?: Array<RuntimeDiagnosticField>;
    };
    export type RuntimeDiagnosticField = {
        key: string;
        value: string;
    };
    /**
     * Runtime provenance attached to a diagnostic without depending on a host
     * transport binding type.
     */
    export type RuntimeDiagnosticRuntimeBinding = {
        instanceId: CanonicalU64;
        generation: CanonicalU64;
        controlRevision: CanonicalU64;
    };
    export type RuntimeDiagnosticSeverity = "debug" | "info" | "warning" | "error";
}
declare module "@rusty-engine/live-debug/internal/live-debug-client/src/index" {
    /**
     * Transport-neutral client for the product-owned generated live-debug catalog.
     * Descriptor data is read-only help/completion data; this client never derives
     * command schemas or dispatches anything except one command-line string.
     */
    import type { ProductHostDebugCatalog, ProductHostDebugCommandDescriptor, ProductHostDiagnosticsReadResponse, RuntimeDiagnosticEvent } from "@rusty-engine/live-debug/internal/live-debug-client/src/generated/contracts";
    export * from "@rusty-engine/live-debug/internal/live-debug-client/src/generated/contracts";
    /** A command's outcome: the host answers 200 or 422 with the message as text. */
    export interface LiveDebugResult {
        readonly succeeded: boolean;
        readonly message: string;
    }
    export interface LiveDebugTransport {
        catalog(signal?: AbortSignal): Promise<ProductHostDebugCatalog>;
        execute(command: string, signal?: AbortSignal): Promise<LiveDebugResult>;
        diagnostics?(after?: string, signal?: AbortSignal): Promise<ProductHostDiagnosticsReadResponse>;
    }
    export interface LiveDebugHttpTransportOptions {
        /** Defaults to the current page origin, preserving same-origin product-host use. */
        readonly origin?: string;
        readonly fetch?: typeof globalThis.fetch;
    }
    /** Creates the default same-origin HTTP transport without owning UI state. */
    export function createLiveDebugHttpTransport(options?: LiveDebugHttpTransportOptions): LiveDebugTransport;
    /** Small UI/CLI-neutral helper for catalog-derived completion. */
    export function completeLiveDebug(catalog: ProductHostDebugCatalog, prefix: string): readonly ProductHostDebugCommandDescriptor[];
    /**
     * Computes how old a diagnostic event is at the response read clock. This is
     * distinct from any age fact carried in the event's own fields.
     */
    export function diagnosticEventAgeMilliseconds(batch: ProductHostDiagnosticsReadResponse, event: RuntimeDiagnosticEvent): number | null;
}
declare module "@rusty-engine/live-debug/internal/live-debug-panel/src/live-debug-panel-model" {
    import type { ProductHostDebugCommandDescriptor, ProductHostRuntimeBinding, ProductHostUpdateAttribution } from "@rusty-engine/live-debug/internal/live-debug-client/src/index";
    export const LIVE_DEBUG_PANEL_MAX_TRANSCRIPT_ENTRIES = 128;
    /** The optional panel's DOM-only placement; it has no product-state meaning. */
    export type LiveDebugPanelPresentation = 'inline' | 'dock' | 'overlay';
    export interface LiveDebugTranscriptEntry {
        readonly command: string;
        readonly message: string;
        readonly succeeded: boolean;
    }
    export function appendLiveDebugTranscript(entries: readonly LiveDebugTranscriptEntry[], entry: LiveDebugTranscriptEntry): readonly LiveDebugTranscriptEntry[];
    export function commandSummary(command: ProductHostDebugCommandDescriptor): string;
    export function historyCommand(history: readonly string[], cursor: number | null, direction: -1 | 1): {
        readonly cursor: number | null;
        readonly command: string;
    };
    /** Formats the exact runtime incarnation without assigning any game meaning to it. */
    export function runtimeIncarnationLabel(runtime: ProductHostRuntimeBinding | null): string;
    /** Labels a completed C# callback and its separate Rust post-callback work. */
    export function updateAttributionLabel(sample: ProductHostUpdateAttribution): string;
}
declare module "@rusty-engine/live-debug/internal/live-debug-panel/src/live-debug-panel" {
    import { type LiveDebugTransport } from "@rusty-engine/live-debug/internal/live-debug-client/src/index";
    import { type LiveDebugPanelPresentation } from "@rusty-engine/live-debug/internal/live-debug-panel/src/live-debug-panel-model";
    export interface LiveDebugPanelOptions {
        /** The host must opt in before the panel creates or uses a transport. */
        readonly enabled: boolean;
        /** A packaged host can retain transport ownership by supplying one. */
        readonly transport: LiveDebugTransport | null;
        readonly presentation: LiveDebugPanelPresentation;
    }
    /**
     * Optional developer UI for the product-owned live-debug host. It has no
     * product state or command semantics: it only presents the generated catalog
     * and forwards one raw command line through a host-supplied transport.
     */
    export class LiveDebugPanel {
        #private;
        /** The mount-owned node; the caller-owned host stays reusable after dispose. */
        readonly element: HTMLElement;
        constructor(document: Document, options: LiveDebugPanelOptions);
        reconnect(): void;
        execute(): void;
        clearTranscript(): void;
        copyTranscript(): Promise<void>;
        dispose(): void;
    }
}
declare module "@rusty-engine/live-debug/internal/live-debug-panel/src/renderer-metrics-widget" {
    import { type LiveDebugTransport } from "@rusty-engine/live-debug/internal/live-debug-client/src/index";
    /** Explicit, product-owned configuration for one optional renderer metrics widget. */
    export interface RendererMetricsWidgetMountOptions {
        /**
         * When supplied, establishes the shared Engine widget state at mount. Omit
         * it to preserve the Engine default (hidden) or a console-selected state.
         */
        readonly initiallyVisible?: boolean;
        /** Uses the widget's same-origin HTTP transport when omitted. */
        readonly transport?: LiveDebugTransport;
    }
    /** Releases polling and the DOM node owned by one widget mount. */
    export interface RendererMetricsWidgetMount {
        dispose(): void;
    }
    /**
     * Mounts a small Engine-owned DOM readout of the latest admitted renderer
     * diagnostics. It only polls the live-debug route; it neither schedules a
     * browser animation frame nor submits renderer work.
     */
    export function mountRendererMetricsWidget(host: HTMLElement, options?: RendererMetricsWidgetMountOptions): RendererMetricsWidgetMount;
}
declare module "@rusty-engine/live-debug" {
    import type { LiveDebugTransport } from "@rusty-engine/live-debug/internal/live-debug-client/src/index";
    import type { LiveDebugPanelPresentation } from "@rusty-engine/live-debug/internal/live-debug-panel/src/live-debug-panel-model";
    export { mountRendererMetricsWidget, type RendererMetricsWidgetMount, type RendererMetricsWidgetMountOptions, } from "@rusty-engine/live-debug/internal/live-debug-panel/src/renderer-metrics-widget";
    export { createLiveDebugHttpTransport, type ProductHostDebugCatalog, type LiveDebugHttpTransportOptions, type LiveDebugResult, type LiveDebugTransport, } from "@rusty-engine/live-debug/internal/live-debug-client/src/index";
    /** Explicit, product-owned configuration for one optional live-debug panel. */
    export interface LiveDebugPanelMountOptions {
        /** False keeps the mounted panel inert: it does not contact a debug host. */
        readonly enabled: boolean;
        /** Uses the panel's same-origin HTTP transport when omitted. */
        readonly transport?: LiveDebugTransport;
        /** Controls only the panel's DOM presentation. */
        readonly presentation?: LiveDebugPanelPresentation;
    }
    /** Releases the panel's DOM and every request owned by this mounted panel. */
    export interface LiveDebugPanelMount {
        dispose(): void;
    }
    /**
     * Mounts the optional Engine-owned debug UI into a product-owned element.
     * The panel receives no product state and exposes no command semantics: it
     * only forwards raw command lines through the injected or same-origin client.
     */
    export function mountLiveDebugPanel(host: HTMLElement, options: LiveDebugPanelMountOptions): Promise<LiveDebugPanelMount>;
}
