[package]
name = "projector-probe-before"
version = "0.0.0"
edition = "2021"
publish = false

[workspace]

[dependencies]
render-model = { git = "https://github.com/FuzzySlipper/rusty-engine.git", rev = "64a9b164b2013bfc1d558c397005e837552a5ef3" }
render-projection = { git = "https://github.com/FuzzySlipper/rusty-engine.git", rev = "64a9b164b2013bfc1d558c397005e837552a5ef3" }

[profile.release]
debug = false
