[package]
name = "bootstrap-raw"
version.workspace = true
edition.workspace = true
publish.workspace = true
rust-version.workspace = true

[dependencies]
bootstrap-fixture.workspace = true
render-model.workspace = true
wgpu = "30.0.1"
pollster.workspace = true
bytemuck.workspace = true
glam.workspace = true
